force-app/main/default/objects/Currency_Exchange__c/Currency_Exchange__c.object-meta.xml
<CustomObject>
    <label>Currency Exchange</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Market Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency_Exchange__c/fields/baseCurrency__c.field-meta.xml
<CustomField>
    <fullName>baseCurrency__c</fullName>
    <label>baseCurrency</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Currency_Exchange__c/fields/currency__c.field-meta.xml
<CustomField>
    <fullName>currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CurrencyExchangeTriggerHandler.cls
public with sharing class CurrencyExchangeTriggerHandler {
    public static void handleCreatedRecords(Map<Id, Currency_Exchange__c> newRecords) {
        Set<Id> recordIds = new Set<Id>();
        for (Currency_Exchange__c record : newRecords.values()){
            recordIds.add(record.Id);
        }
        
        if(!recordIds.isEmpty() && !System.isFuture()){
            ExchangeRateController2.doGetExchange(recordIds);
            System.debug('recordIds '+recordIds);
        }
    }
    
     public static void handleUpdatedRecords(Map<Id, Currency_Exchange__c> newRecords, Map<Id, Currency_Exchange__c> oldRecordsMap) {
        Set<Id> recordIds = new Set<Id>();
        for (Currency_Exchange__c record : newRecords.values()){
            
            Currency_Exchange__c oldCurExchRec = oldRecordsMap.get(record.id);
            if( record.currency__c != oldCurExchRec.currency__c || record.baseCurrency__c != oldCurExchRec.baseCurrency__c){
                 recordIds.add(record.Id);
            }
           
        }
          
        if(!recordIds.isEmpty() && !System.isFuture()){
            ExchangeRateController2.doGetExchange(recordIds);
            System.debug('recordIds '+recordIds);
        }
    }
    
}