force-app/main/default/objects/Currency_Exchange__c/Currency_Exchange__c.object-meta.xml
<CustomObject>
    <label>Currency Exchange</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Market Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency_Exchange__c/fields/currency__c.field-meta.xml
<CustomField>
    <fullName>currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CurrencyExchangeTriggerHandlerTest.cls
@isTest
public class CurrencyExchangeTriggerHandlerTest {
    @TestSetup static void insertingTestData() {
	  Currency_Exchange__c curExch = new Currency_Exchange__c (
            
            Currency__c = 'GBP'
        );
        insert curExch;
}
    
    static testMethod void testHandleCreatedRecords() {
        
        map<id,Currency_Exchange__c > curExcMap = new map<id,Currency_Exchange__c>();
        // Create a Currency_Exchange__c record
        Currency_Exchange__c curExch = new Currency_Exchange__c (
            
            Currency__c = 'GBP'
        );
        insert curExch;
        curExcMap.put(curExch.Id, curExch);
  
        Test.startTest();
          CurrencyExchangeTriggerHandler.handleCreatedRecords(curExcMap);
        Test.stopTest();
      

            
            }
    
    static testMethod void testHandleUpdatedRecords() {
        // Create a Currency_Exchange__c record
        Currency_Exchange__c curExch = new Currency_Exchange__c (
            
            Currency__c = 'EUR'
        );
        insert curExch;
        
        // Update the Currency__c field
        curExch.Currency__c = 'EUR';
        update curExch;
        
        
    }
}